import { writable } from 'svelte/store'

export const API_URL: string = 'http://localhost:8000/api'

export const websiteName: string = 'Talentify'

export const collapseSidebar = writable(false)

export const languages = [
	'Arabic',
	'Chinese',
	'English',
	'French',
	'German',
	'Hindi',
	'Italian',
	'Japanese',
	'Portuguese',
	'Russian',
	'Spanish',
	'Polish',
	'Dutch',
	'Korean',
	'Turkish',
	'Vietnamese',
	'Czech',
	'Swedish',
	'Danish',
	'Finnish',
	'Norwegian',
	'Hungarian',
	'Romanian',
	'Greek',
	'Ukrainian',
	'Thai',
	'Indonesian',
	'Malay',
	'Catalan',
	'Hebrew',
	'Croatian',
	'Slovak',
	'Lithuanian',
	'Slovenian',
	'Latvian',
	'Estonian',
	'Bulgarian',
	'Serbian',
	'Macedonian',
	'Bosnian',
	'Albanian',
	'Montenegrin',
	'Belarusian',
	'Uzbek',
	'Azerbaijani',
	'Kazakh',
	'Turkmen',
	'Tatar',
	'Kyrgyz',
	'Armenian',
	'Georgian',
	'Moldovan',
	'Tajik',
	'Kirghiz',
	'Afrikaans',
	'Amharic',
	'Bengali',
	'Burmese',
	'Cebuano',
	'Chichewa',
	'Filipino',
	'Hausa',
	'Igbo',
	'Javanese',
	'Kannada',
	'Khmer',
	'Lao',
	'Malagasy',
	'Malayalam',
	'Marathi',
	'Nepali',
	'Punjabi',
	'Sinhala',
	'Somali',
	'Sundanese',
	'Tamil',
	'Telugu',
	'Uzbek',
	'Zulu'
]

export const degrees = [
	'Bac +2',
	'License',
	"Bachelor's",
	"Master's",
	'Engineering',
	'PhD',
	"Associate's",
	'Diploma',
	'Certificate',
	'Postgraduate Diploma',
	'Doctorate',
	'Professional Degree',
	'Vocational Training',
	'MBA',
	'MSc',
	'MA',
	'LLB',
	'LLM',
	'MD',
	'DDS',
	'DVM',
	'JD',
	'BTech',
	'MTech',
	'BEng'
]

export const technicalSkills = [
	'Programming',
	'Web Development',
	'Database Management',
	'Cybersecurity',
	'Networking',
	'Cloud Computing',
	'Data Analysis',
	'Machine Learning',
	'Artificial Intelligence',
	'DevOps',
	'System Administration',
	'Software Development',
	'Mobile App Development',
	'Version Control (e.g., Git)',
	'Containerization (e.g., Docker)',
	'Virtualization',
	'API Development',
	'IT Support',
	'Technical Writing',
	'Blockchain',
	'IoT (Internet of Things)',
	'Game Development',
	'Big Data',
	'Agile Methodologies',
	'Project Management Tools (e.g., Jira)'
]

export const softSkills = [
	'Communication',
	'Teamwork',
	'Problem Solving',
	'Time Management',
	'Adaptability',
	'Critical Thinking',
	'Creativity',
	'Leadership',
	'Interpersonal Skills',
	'Conflict Resolution',
	'Emotional Intelligence',
	'Negotiation',
	'Customer Service',
	'Decision Making',
	'Work Ethic',
	'Attention to Detail',
	'Stress Management',
	'Self-Motivation',
	'Networking',
	'Public Speaking',
	'Empathy',
	'Collaboration',
	'Flexibility',
	'Active Listening',
	'Organizational Skills'
]

export const categoryList = [
	'IT Support',
	'Artificial Intelligence',
	'Database Management',
	'Software Development',
	'Quality Assurance',
	'Cybersecurity',
	'Networking',
	'Web Development',
	'Cloud Computing',
	'Data Analysis',
	'Machine Learning',
	'DevOps',
	'System Administration',
	'Mobile App Development',
	'Game Development',
	'Big Data',
	'Project Management'
]

export const tagList = [
	'data',
	'software',
	'developer',
	'engineer',
	'analyst',
	'manager',
	'consultant',
	'specialist',
	'architect',
	'designer',
	'administrator',
	'support',
	'technician',
	'security',
	'network',
	'web',
	'cloud',
	'database',
	'AI',
	'ML',
	'IoT',
	'blockchain',
	'full-stack',
	'front-end',
	'back-end',
	'mobile',
	'game',
	'QA',
	'testing',
	'automation',
	'agile',
	'scrum',
	'kanban',
	'lean',
	'CI/CD',
	'DevOps'
]

export const requiredSkills = [
	'JavaScript',
	'Python',
	'Java',
	'HTML',
	'CSS',
	'React',
	'Node.js',
	'TypeScript',
	'SQL',
	'NoSQL',
	'Git',
	'Docker',
	'Kubernetes',
	'AWS',
	'Azure',
	'Google Cloud',
	'Linux',
	'REST API',
	'GraphQL',
	'Agile/Scrum',
	'DevOps',
	'CI/CD',
	'Microservices',
	'Spring Boot',
	'Django',
	'Flask',
	'Ruby on Rails',
	'Angular',
	'Vue.js',
	'MongoDB',
	'PostgreSQL',
	'MySQL',
	'PHP',
	'C#',
	'ASP.NET',
	'Machine Learning',
	'Data Science',
	'Artificial Intelligence',
	'Blockchain',
	'Cybersecurity',
	'Mobile Development',
	'Swift',
	'Kotlin',
	'Objective-C',
	'UX/UI Design',
	'Project Management',
	'TDD (Test-Driven Development)',
	'Continuous Integration',
	'Big Data',
	'SaaS',
	'Serverless Architecture',
	'Networking',
	'Jenkins',
	'Terraform',
	'Ansible'
]
